# Generated by Django 3.2.4 on 2021-06-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_person', models.CharField(blank=True, max_length=254, null=True)),
                ('current_score', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
