# Generated by Django 3.2.4 on 2021-06-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_person', models.CharField(blank=True, max_length=254, null=True)),
                ('team_1', models.CharField(blank=True, max_length=254, null=True)),
                ('team_2', models.CharField(blank=True, max_length=254, null=True)),
                ('team_3', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
