# Generated by Django 3.2.4 on 2021-06-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='total_goals_against',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='total_goals_for',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
