# Generated by Django 3.2.4 on 2021-06-17 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210613_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual_teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_team', models.CharField(blank=True, max_length=254, null=True)),
                ('team_goals_for', models.IntegerField(blank=True, default=0, null=True)),
                ('team_goals_against', models.IntegerField(blank=True, default=0, null=True)),
                ('team_knocked_out_groups', models.BooleanField(default=False)),
                ('team_knocked_out', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1_goals', models.IntegerField(blank=True, default=0, null=True)),
                ('team_2_goals', models.IntegerField(blank=True, default=0, null=True)),
                ('team_1_score', models.IntegerField(blank=True, default=0, null=True)),
                ('team_2_score', models.IntegerField(blank=True, default=0, null=True)),
                ('team_1_red_card', models.IntegerField(blank=True, default=0, null=True)),
                ('team_2_red_card', models.IntegerField(blank=True, default=0, null=True)),
                ('team_1_win_rival', models.BooleanField()),
                ('team_2_win_rival', models.BooleanField()),
                ('team_1_draw_rival', models.BooleanField()),
                ('team_2_draw_rival', models.BooleanField()),
                ('name_of_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Player', to='home.players')),
                ('team_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_1', to='home.individual_teams')),
                ('team_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_2', to='home.individual_teams')),
            ],
        ),
    ]
