# Generated by Django 3.2.4 on 2021-06-17 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_individual_teams_matches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='name_of_person',
        ),
        migrations.AddField(
            model_name='matches',
            name='name_of_person_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Player_1', to='home.players'),
        ),
        migrations.AddField(
            model_name='matches',
            name='name_of_person_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Player_2', to='home.players'),
        ),
        migrations.AddField(
            model_name='teams',
            name='auto_team_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_team_1', to='home.individual_teams'),
        ),
        migrations.AddField(
            model_name='teams',
            name='auto_team_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_team_2', to='home.individual_teams'),
        ),
        migrations.AddField(
            model_name='teams',
            name='auto_team_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_team_3', to='home.individual_teams'),
        ),
    ]
