# Generated by Django 3.2.4 on 2021-06-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210617_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='own_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
